name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy env file
        run: cp /home/ashok/Travel-Planner-Backend/.env .env

      - name: Rebuild and restart
        run: docker compose up -d --build --remove-orphans

      - name: Clean up old images
        if: always()
        run: docker image prune -f
